### ISSUE TITLE
Is the audio presented to the viewer during fixation collection?

### ISSUE THREAD

**Issue by zijunwei** [wenguanwang/DHF1K#1]
Hi, thanks for collecting such a valuable dataset!
Several things I want to clarify with you:
1. I noticed they videos are with audios. Are the viewers accessible to them during the data collection? 
2. As for the 1000 video clips, are they the complete clips that you directly downloaded from YouTube or you randomly cut some them from the raw videos?

Many thanks!

**Comment by wenguanwang** [comment]
@zijunwei 
Thanks for your interest.
1. The viewers did not access the audios.
2. We typically select a part of the original YouTube video, since the original one is often too long and with many useless shots and shot-cuts.

**Comment by zijunwei** [comment]
Are there any rules for you to pick parts of the original videos? For example, shot boundaries? What if the video is long but with only single shot?

**Comment by wenguanwang** [comment]
@zijunwei The length of the video is no longer than 1min and no shorter than 15 seconds.

**Comment by wjakobw** [comment]
Hi, I calculated some [stats](https://github.com/wjakobw/DHF1K/blob/master/stats.md) for the dataset, including video lengths. There are more than zero shot-cuts, see for example 007.AVI . Thanks again for providing the dataset!
