### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by Saixiaoma** [wenguanwang/DHF1K#15]
can you provide the pre-trained model?

**Comment by wenguanwang** [comment]
@Saixiaoma Our trained model can be found at the google disk, as mentioned in the readme.

**Comment by Saixiaoma** [comment]
OK，thanks

**Comment by Saixiaoma** [comment]
> @Saixiaoma Our trained model can be found at the google disk, as mentioned in the readme.

thanks
