### ISSUE TITLE
Dataset license

### ISSUE THREAD

**Issue by SijieSong** [wenguanwang/DHF1K#17]
Hi,

Thanks for the great work. Could you please provide a license for the dataset?

**Comment by wenguanwang** [comment]
Hi, 

Thanks for your reminder. 

Related terms are added. 

Thanks,
Wenguan

**Comment by SijieSong** [comment]
> Hi,
> 
> Thanks for your reminder.
> 
> Related terms are added.
> 
> Thanks,
> Wenguan

Thank you very much.

Sijie
