### ISSUE TITLE
Testing setting of Hollywood2 dataset

### ISSUE THREAD

**Issue by kylemin** [wenguanwang/DHF1K#4]
Did you use the whole fixation points when training and testing Hollywood2 dataset?
Or, did you filter out some points? (e.x. filters out the points at image edge, ....)
Also, did you use the whole 884 test videos when testing Hollywood2?
How did you sync the fixation points with the video?

I am asking you this because I want to replicate the same result on Hollywood2 dataset.
Could you provide a more detailed information of your setting?
(I divided the videos by using shot bounds, as you mentioned)

**Comment by wenguanwang** [comment]
@kylemin 
Thanks for your interest.

All the fixation points are used. 

All the 884 test videos (divided into shots) are used for evaluation.

For Hollywood2 and UCF, I directly use following function to blur the fixation map:

densityMap = imfilter(fixations,fspecial('gaussian',150,20),'replicate').

**Comment by wenguanwang** [comment]
@kylemin 

BTW, only the fixations lie within the images are used.

**Comment by kylemin** [comment]
Got it, thank you!
