### ISSUE TITLE
Gaussian blurring of fixation map of Hollywood2 and UCFSports

### ISSUE THREAD

**Issue by kylemin** [wenguanwang/DHF1K#5]
I checked that the fixation map of DHF1K is blurred by width 30 gaussian kernel.
Did you use the same width for the Hollywood2 and UCFSports dataset?

**Comment by wenguanwang** [comment]
I use this function for blurring the fixations in DHF1K.

[x,y]=find(fixations);
densityMap= make_gauss_masks(y,x,[video_res_y,video_res_x]);
[make_gauss_masks.zip](https://github.com/wenguanwang/DHF1K/files/2459096/make_gauss_masks.zip)

**Comment by kylemin** [comment]
Thank you!
