### ISSUE TITLE
UCF download link?

### ISSUE THREAD

**Issue by Linardos** [wenguanwang/DHF1K#7]
You mentioned in a previous issue : 

> Hi, all, the data of Hollywood-2 and UCF have been uploaded. 
> 
> The code (ACLNet) and dataset (DHF1K with raw gaze records, UCF-sports are new added!) can be downloaded from:
> 
> Google disk：https://drive.google.com/open?id=1sW0tf9RQMO4RR7SyKhU8Kmbm4jwkFGpQ
> 
> Baidu pan: https://pan.baidu.com/s/110NIlwRIiEOTyqRwYdDnVg
> 
> The Hollywood-2 (74.6G) can be downloaded from:
> 
> Google disk：https://drive.google.com/open?id=1vfRKJloNSIczYEOVjB4zMK8r0k4VJuWk
> 
> _Originally posted by @wenguanwang in https://github.com/wenguanwang/DHF1K/issues/2#issuecomment-428440091_
> 

Is there also a link for the UCF-sports dataset?

**Comment by wenguanwang** [comment]
@Linardos , Yes, UCF can also be found at https://drive.google.com/open?id=1sW0tf9RQMO4RR7SyKhU8Kmbm4jwkFGpQ

**Comment by Linardos** [comment]
Cool, thanks!
