### ISSUE TITLE
Annotations for only 26 videos

### ISSUE THREAD

**Issue by navyasri1** [wenguanwang/DHF1K#8]
After downloading the dataset, the annotation folder has annotations for only 26 videos. How can I get the annotations of remaining videos?

**Comment by wenguanwang** [comment]
@navyasri1 , please specify your issue. Which download link do you use? In addition, many people have download our annotation, maybe you should check if it is caused by any other problem.

**Comment by navyasri1** [comment]
I downloaded from here [link](https://drive.google.com/drive/folders/1sW0tf9RQMO4RR7SyKhU8Kmbm4jwkFGpQ). Annotation.rar has maps and fixations for 26 people
